services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: frontend_app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=development
